### ISSUE TITLE
"from tap import Tap" error

### ISSUE THREAD

**Issue by cxw-droid** [python-tap/tappy#124]
I installed tap using `pip install tap.py`. There is an error when `from tap import Tap` as follows:
>from tap import Tap
ImportError: cannot import name 'Tap' from 'tap' (/home/xxx/miniconda3/envs/torch1.10/lib/python3.9/site-packages/tap/__init__.py)

The `__init__.py` is:
>from .runner import TAPTestRunner

>__all__ = ["TAPTestRunner"]
__version__ = "3.1"

The python version is 3.9.12 and pytorch is 1.10.1

**Comment by mblayman** [comment]
This is not an error because there is no documented (or undocumented!) API named `Tap`, so I'm not sure what you expected to happen here.

The documented programmatic API is found here: https://tappy.readthedocs.io/en/latest/consumers.html#api tappy includes a test loader, parser, and interface for interacting with individual TAP lines.

**Comment by cxw-droid** [comment]
I found the reason. There is another tap package [Typed Argument Parser (Tap)](https://github.com/swansonk14/typed-argument-parser)

**Comment by mblayman** [comment]
Cool. I'm glad you figured it out. I'll file that bit of knowledge away the next time someone mentions `from tap import Tap`. Good luck with your coding effort!
