### ISSUE TITLE
Output 'TAP version 13' to .tap files 

### ISSUE THREAD

**Issue by richard-bosworth** [python-tap/tappy#78]
If version 13 is in use (or enabled) then print 'TAP version 13' to any .tap files created. Donwstream consumers in Tappy require that line to be present to attempt to load YAML blocks so it would be good for the producer to output it.

I've done this locally but have never submitted to a GitHub project before so thought I'd ask first - happy to share more details of why this would be good, or the code I've used, and also happy to submit for PR if that's easiest.

**Comment by mblayman** [comment]
@richard-bosworth tappy currently has no ability to *produce* YAML blocks. The latest version that I pushed out added the ability to *consume* YAML blocks via the parser API.

Since the output for tappy is currently version 12 format, I intentionally left off `TAP version 13` to be maximally compatible with other consumers.

I'm happy to consider adding TAP version 13, but I'm not sure that I see the advantage or need at the moment. We can use this issue to weight the pros/cons and see if adding the version 13 identifier makes sense.

**Comment by richard-bosworth** [comment]
@mblayman sounds good - I should probably clarify that I only wanted the addition of the version 13 line in the case where the moreitertools and yaml libraries are installed. In my sample code I used the same try except that is in the parser.py module to check whether the version 13 line should be added. Should I push that up?

The reason it would be good for me is that we are using the YAML blocks in donwstream systems to help monitor tests across languages as part of CI.

**Comment by richard-bosworth** [comment]
Brilliant - I'll put up a PR

**Comment by richard-bosworth** [comment]
Submitted the PR now - thanks!
