### ISSUE TITLE
Add command-line interface like python3 -munitest

### ISSUE THREAD

**Issue by rossburton** [python-tap/tappy#84]
It would be *really* neat if there was a way to run existing `unittest`-based test suites with something like `python3 -mtappytest`.  Something like this mostly works already:

```
import tap, unittest
runner = tap.runner.TAPTestRunner()
runner.set_stream(True)
unittest.main(module=None, testRunner=runner)
```

**Comment by mblayman** [comment]
I would certainly be open to this idea as a PR. Throwing down some requirements that I would expect:
* Run as `python3 -m tappy` since `tappy` is the package name.
* Use unittest's autodiscovery mechanism.
* Have test coverage to prove it works.
* Add an integration test for CI on tappy itself.

`tappy/tests/run.py` would be a reasonable place to start from for an idea of how to get going for whomever is interested in giving this a shot.

**Comment by rossburton** [comment]
This is easier than it looks at first: https://github.com/rossburton/tappy/commit/c8fb29e3a96f4977716cb59592873601f0f82c35

```
ross@flashheart ~/Local/mess/24/tappy (main *%)
$ python3 -mtap # as that is the module name
# TAP results for TestAdapter
ok 1 The adapter has a TAP filename.
ok 2 Add an expected failure for a not ok todo test line.
ok 3 Add a success for an ok test line.
ok 4 Add an unexpected success for an ok todo test line.
ok 5 Add a skip when a test line contains a skip directive.
# TAP results for TestDirective
ok 6 test_finds_simplest_skip (tap.tests.test_directive.TestDirective)
ok 7 test_finds_simplest_todo (tap.tests.test_directive.TestDirective)
ok 8 test_finds_skip (tap.tests.test_directive.TestDirective)
ok 9 test_finds_todo (tap.tests.test_directive.TestDirective)
ok 10 Only match SKIP directives at the beginning.
...
```

**Comment by mblayman** [comment]
Oops... it's been a while since I worked on tappy. Thanks for the reminder that `tap` is the package name. I've updated the requirements to reflect that.
